# see https://github.com/hlascelles/que-scheduler#schedule-configuration
UpdateThreadsMetadataJob:
  cron: '*/5 * * * *'

UpdateThreadsRepliesJob:
  cron: '*/20 * * * *'

UpdateUsersDetailsJob:
  cron: '*/20 * * * *'
